merge

diff --git a/roles/zsh/files/zshrc b/roles/zsh/files/zshrc
--- a/roles/zsh/files/zshrc
+++ b/roles/zsh/files/zshrc
@@ -1,21 +1,22 @@
-export ZSH=$HOME/.oh-my-zsh
+ZSH=$HOME/.oh-my-zsh
 
-export BASE16_SHELL_SET_BACKGROUND=false
-~/.zsh_theme.sh
-
+BASE16_SHELL_SET_BACKGROUND=false
+~/.zsh_color_theme.sh
 ZSH_THEME="agnoster"
 
 COMPLETION_WAITING_DOTS="true"
 
-plugins=(archlinux docker docker-compose git thefuck yarn zsh-syntax-highlighting)
+REPORTTIME=10
+plugins=(archlinux docker docker-compose thefuck zsh-syntax-highlighting)
 
 # User configuration
 export GOPATH=$HOME/.go
 export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/.dotfiles/bin:$GOPATH/bin:$HOME/.local/bin"
+export EDITOR=vim
 
 export MAVEN_OPTS=-Xmx2048m
 
-PATH="$HOME/.node_modules/bin:$PATH"
+export PATH="$PATH:$HOME/.node_modules/bin"
 export npm_config_prefix=~/.node_modules
 
 source $ZSH/oh-my-zsh.sh
@@ -42,3 +43,28 @@ s_whichhostgroup() {
 }
 
 eval "$(direnv hook zsh)"
+copy3d() {
+    DATA_DIR=$1
+    MOUNT_DIR=/mnt/stick
+    STICK_DIR=$MOUNT_DIR/prints/
+
+    if [ "S1" = "" -o "$2" = "" ]; then
+      echo "Missing parameter:"
+      echo "copy3d folder_with_ctb_files /dev/sdXX"
+      return 1
+    fi
+
+    sudo mount $2 $MOUNT_DIR
+
+    for i in $(find $DATA_DIR -name "*.ctb"); do
+        ls "$STICK_DIR/$(basename $i)" > /dev/null 2>&1
+        if [ "$?" -ne "0" ]; then
+            cp "$i" $STICK_DIR/
+            echo "copied $(basename $i)"
+        fi
+    done
+
+    sudo umount $MOUNT_DIR
+    sync
+    echo "\e[1mDone, remove USB Stick\e[7"
+}
